/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanduanRouteImport } from './routes/panduan'
import { Route as AlatAturRouteImport } from './routes/alat.atur'
import { Route as AlatKonversiRouteImport } from './routes/alat.konversi'
import { Route as AlatOptimalkanRouteImport } from './routes/alat.optimalkan'
import { Route as AlatSlugRouteImport } from './routes/alat.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanduanRoute = PanduanRouteImport.update({
  id: '/panduan',
  path: '/panduan',
  getParentRoute: () => rootRouteImport,
} as any)
const AlatAturRoute = AlatAturRouteImport.update({
  id: '/alat/atur',
  path: '/alat/atur',
  getParentRoute: () => rootRouteImport,
} as any)
const AlatKonversiRoute = AlatKonversiRouteImport.update({
  id: '/alat/konversi',
  path: '/alat/konversi',
  getParentRoute: () => rootRouteImport,
} as any)
const AlatOptimalkanRoute = AlatOptimalkanRouteImport.update({
  id: '/alat/optimalkan',
  path: '/alat/optimalkan',
  getParentRoute: () => rootRouteImport,
} as any)
const AlatSlugRoute = AlatSlugRouteImport.update({
  id: '/alat/$slug',
  path: '/alat/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/panduan': typeof PanduanRoute
  '/alat/atur': typeof AlatAturRoute
  '/alat/konversi': typeof AlatKonversiRoute
  '/alat/optimalkan': typeof AlatOptimalkanRoute
  '/alat/$slug': typeof AlatSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/panduan': typeof PanduanRoute
  '/alat/atur': typeof AlatAturRoute
  '/alat/konversi': typeof AlatKonversiRoute
  '/alat/optimalkan': typeof AlatOptimalkanRoute
  '/alat/$slug': typeof AlatSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/panduan': typeof PanduanRoute
  '/alat/atur': typeof AlatAturRoute
  '/alat/konversi': typeof AlatKonversiRoute
  '/alat/optimalkan': typeof AlatOptimalkanRoute
  '/alat/$slug': typeof AlatSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/panduan' | '/alat/atur' | '/alat/konversi' | '/alat/optimalkan' | '/alat/$slug'
  fileRoutesByTo: FileRoutesByTo
  fileRoutesById: FileRoutesById
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/panduan' | '/alat/atur' | '/alat/konversi' | '/alat/optimalkan' | '/alat/$slug'
  id: '__root__' | '/' | '/panduan' | '/alat/atur' | '/alat/konversi' | '/alat/optimalkan' | '/alat/$slug'
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PanduanRoute: typeof PanduanRoute
  AlatAturRoute: typeof AlatAturRoute
  AlatKonversiRoute: typeof AlatKonversiRoute
  AlatOptimalkanRoute: typeof AlatOptimalkanRoute
  AlatSlugRoute: typeof AlatSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panduan': {
      id: '/panduan'
      path: '/panduan'
      fullPath: '/panduan'
      preLoaderRoute: typeof PanduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alat/atur': {
      id: '/alat/atur'
      path: '/alat/atur'
      fullPath: '/alat/atur'
      preLoaderRoute: typeof AlatAturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alat/konversi': {
      id: '/alat/konversi'
      path: '/alat/konversi'
      fullPath: '/alat/konversi'
      preLoaderRoute: typeof AlatKonversiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alat/optimalkan': {
      id: '/alat/optimalkan'
      path: '/alat/optimalkan'
      fullPath: '/alat/optimalkan'
      preLoaderRoute: typeof AlatOptimalkanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alat/$slug': {
      id: '/alat/$slug'
      path: '/alat/$slug'
      fullPath: '/alat/$slug'
      preLoaderRoute: typeof AlatSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PanduanRoute: PanduanRoute,
  AlatAturRoute: AlatAturRoute,
  AlatKonversiRoute: AlatKonversiRoute,
  AlatOptimalkanRoute: AlatOptimalkanRoute,
  AlatSlugRoute: AlatSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
